# Server
server.port=8080

# Database (PostgreSQL from Render)
spring.datasource.url=jdbc:postgresql://dpg-d6of9h75r7bs73e4f4gg-a/employee_igc4
spring.datasource.username=employee_igc4_user
spring.datasource.password=QXBCrQOq4XdpWbBTBv21XzOofSAzwtgj
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION}

# Twilio
# twilio.account-sid=${TWILIO_SID}
# twilio.auth-token=${TWILIO_AUTH_TOKEN}
# twilio.phone-number=${TWILIO_PHONE_NUMBER}

# CORS
app.cors.allowed-origins=https://your-app.vercel.app
# Logging
logging.level.com.anurag=DEBUG